#!/bin/env sh

# Type checks a Python project with mypy.

command='mypy --pretty --strict --ignore-missing-imports'

path=$(pwd)
while :; do
    if [ -f $path/setup.py ]; then
        $command $path
        exit
    fi
    path=$path/..
    if [ ! -d $path ]; then
        echo "Working directory must be inside a Python project."
        exit
    fi
done
