#!/bin/env sh

# Cleans a Python project.

project=${0%/*}/..

srm() {
    [ -e $1 ] && rm -rf $1
}

cd $project
srm .mypy_cache
srm .pytest_cache
srm dialogos/__pycache__
srm tests/__pycache__
srm build
srm .egg-info
